/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/Application.java to edit this template
 */

import java.awt.Color;

/**
 *
 * @author ilmag
 */
public class MainGUI extends javax.swing.JFrame {

    /**
     * Creates new form NewApplication
     */

    private Boolean actionPlaceFurniture = false;


    public MainGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFrame1 = new javax.swing.JFrame();
        jScrollBar1 = new javax.swing.JScrollBar();
        mainMenuPanel = new javax.swing.JPanel();
        lblSims = new javax.swing.JLabel();
        btnChangeSim = new javax.swing.JButton();
        btnAddSim = new javax.swing.JButton();
        scrollPaneListSims = new javax.swing.JScrollPane();
        listSims = new javax.swing.JList<>();
        lblActiveSimInfo = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        lblSimName = new javax.swing.JLabel();
        btnInventory = new javax.swing.JButton();
        btnLocation = new javax.swing.JButton();
        lblKekenyangan = new javax.swing.JLabel();
        lblMood = new javax.swing.JLabel();
        lblKesehatan = new javax.swing.JLabel();
        lblStatus = new javax.swing.JLabel();
        scrollpaneStatus = new javax.swing.JScrollPane();
        textPaneStatus = new javax.swing.JTextPane();
        lblPekerjaan = new javax.swing.JLabel();
        scrollpanePekerjaan = new javax.swing.JScrollPane();
        textpanePekerjaan = new javax.swing.JTextPane();
        lblUang = new javax.swing.JLabel();
        scrollpaneUang = new javax.swing.JScrollPane();
        jTextPane3 = new javax.swing.JTextPane();
        progbarMood = new javax.swing.JProgressBar();
        progbarKekenyangan = new javax.swing.JProgressBar();
        progbarKesehatan = new javax.swing.JProgressBar();
        lblProgbarKekenyangan = new javax.swing.JLabel();
        lblProgbarMood = new javax.swing.JLabel();
        lblProgbarKesehatan = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        dropdownDirection = new javax.swing.JComboBox<>();
        lblSimActions = new javax.swing.JLabel();
        dropdownObject = new javax.swing.JComboBox<>();
        btnMoveToRoom = new javax.swing.JButton();
        btnListObjects = new javax.swing.JButton();
        btnEditRoom = new javax.swing.JButton();
        btnConfirm = new javax.swing.JButton();
        btnLookAtTime = new javax.swing.JButton();
        btnVisitOthers = new javax.swing.JButton();
        btnPlaceFurniture = new javax.swing.JButton();
        btnBuildBuy = new javax.swing.JButton();
        lblObjectActions = new javax.swing.JLabel();
        lblObject = new javax.swing.JLabel();
        lblAction = new javax.swing.JLabel();
        dropdownAction = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        menuBar = new javax.swing.JMenuBar();
        fileMenu = new javax.swing.JMenu();
        loadMenuItem = new javax.swing.JMenuItem();
        saveAsMenuItem = new javax.swing.JMenuItem();
        exitMenuItem = new javax.swing.JMenuItem();
        saveMenuItem = new javax.swing.JMenuItem();
        editMenu = new javax.swing.JMenu();
        cutMenuItem = new javax.swing.JMenuItem();
        copyMenuItem = new javax.swing.JMenuItem();
        pasteMenuItem = new javax.swing.JMenuItem();
        deleteMenuItem = new javax.swing.JMenuItem();
        helpMenu = new javax.swing.JMenu();
        contentsMenuItem = new javax.swing.JMenuItem();
        aboutMenuItem = new javax.swing.JMenuItem();

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        mainMenuPanel.setMaximumSize(new java.awt.Dimension(256, 32767));
        mainMenuPanel.setPreferredSize(new java.awt.Dimension(256, 768));

        lblSims.setFont(new java.awt.Font("Public Sans", 1, 12)); // NOI18N
        lblSims.setText("SIMS");

        btnChangeSim.setText("CHANGE SIM");
        btnChangeSim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChangeSimActionPerformed(evt);
            }
        });

        btnAddSim.setFont(new java.awt.Font("Public Sans", 1, 12)); // NOI18N
        btnAddSim.setText("+");
        btnAddSim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddSimActionPerformed(evt);
            }
        });

        listSims.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Glenn", "Tulus", "Reza", "Melly" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        scrollPaneListSims.setViewportView(listSims);

        lblActiveSimInfo.setFont(new java.awt.Font("Public Sans", 1, 12)); // NOI18N
        lblActiveSimInfo.setText("ACTIVE SIM INFO");

        lblSimName.setFont(new java.awt.Font("Public Sans", 1, 20)); // NOI18N
        lblSimName.setText("Melly");

        btnInventory.setText("INVENTORY");
        btnInventory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInventoryActionPerformed(evt);
            }
        });

        btnLocation.setText("LOCATION");

        lblKekenyangan.setFont(new java.awt.Font("Public Sans", 0, 12)); // NOI18N
        lblKekenyangan.setText("Kekenyangan");

        lblMood.setFont(new java.awt.Font("Public Sans", 0, 12)); // NOI18N
        lblMood.setText("Mood");

        lblKesehatan.setFont(new java.awt.Font("Public Sans", 0, 12)); // NOI18N
        lblKesehatan.setText("Kesehatan");

        lblStatus.setFont(new java.awt.Font("Public Sans", 0, 12)); // NOI18N
        lblStatus.setText("Status");

        textPaneStatus.setText("Memasak");
        scrollpaneStatus.setViewportView(textPaneStatus);

        lblPekerjaan.setFont(new java.awt.Font("Public Sans", 0, 12)); // NOI18N
        lblPekerjaan.setText("Pekerjaan");

        textpanePekerjaan.setText("Programmer $45/hari");
        scrollpanePekerjaan.setViewportView(textpanePekerjaan);

        lblUang.setFont(new java.awt.Font("Public Sans", 0, 12)); // NOI18N
        lblUang.setText("Uang");

        jTextPane3.setText("$2.147.483.647");
        scrollpaneUang.setViewportView(jTextPane3);

        progbarMood.setPreferredSize(new java.awt.Dimension(100, 4));

        progbarKekenyangan.setPreferredSize(new java.awt.Dimension(100, 4));

        progbarKesehatan.setPreferredSize(new java.awt.Dimension(100, 4));

        lblProgbarKekenyangan.setFont(new java.awt.Font("Public Sans", 0, 12)); // NOI18N
        lblProgbarKekenyangan.setText("100");

        lblProgbarMood.setFont(new java.awt.Font("Public Sans", 0, 12)); // NOI18N
        lblProgbarMood.setText("100");

        lblProgbarKesehatan.setFont(new java.awt.Font("Public Sans", 0, 12)); // NOI18N
        lblProgbarKesehatan.setText("100");

        dropdownDirection.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Right", "Left", "Up", "Down" }));
        dropdownDirection.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dropdownDirectionActionPerformed(evt);
            }
        });

        lblSimActions.setFont(new java.awt.Font("Public Sans", 1, 12)); // NOI18N
        lblSimActions.setText("SIM ACTIONS");

        dropdownObject.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Kasur", "Lemari" }));
        dropdownObject.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dropdownObjectActionPerformed(evt);
            }
        });

        btnMoveToRoom.setText("MOVE TO ROOM");
        btnMoveToRoom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMoveToRoomActionPerformed(evt);
            }
        });

        btnListObjects.setText("LIST OBJECTS");
        btnListObjects.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListObjectsActionPerformed(evt);
            }
        });

        btnEditRoom.setText("EDIT ROOM");
        btnEditRoom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditRoomActionPerformed(evt);
            }
        });

        btnConfirm.setText("CONFIRM");
        btnConfirm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfirmActionPerformed(evt);
            }
        });

        btnLookAtTime.setText("LOOK AT TIME");
        btnLookAtTime.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLookAtTimeActionPerformed(evt);
            }
        });

        btnVisitOthers.setText("VISIT OTHERS");
        btnVisitOthers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVisitOthersActionPerformed(evt);
            }
        });

        btnPlaceFurniture.setText("PLACE FURNITURE");
        btnPlaceFurniture.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPlaceFurnitureActionPerformed(evt);
            }
        });

        btnBuildBuy.setText("BUILD/BUY");
        btnBuildBuy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuildBuyActionPerformed(evt);
            }
        });

        lblObjectActions.setFont(new java.awt.Font("Public Sans", 1, 12)); // NOI18N
        lblObjectActions.setText("OBJECT ACTIONS");

        lblObject.setFont(new java.awt.Font("Public Sans", 0, 12)); // NOI18N
        lblObject.setText("Object");

        lblAction.setFont(new java.awt.Font("Public Sans", 0, 12)); // NOI18N
        lblAction.setText("Direction");

        dropdownAction.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tidur" }));
        dropdownAction.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dropdownActionActionPerformed(evt);
            }
        });

        jLabel1.setText("Action");

        javax.swing.GroupLayout mainMenuPanelLayout = new javax.swing.GroupLayout(mainMenuPanel);
        mainMenuPanel.setLayout(mainMenuPanelLayout);
        mainMenuPanelLayout.setHorizontalGroup(
            mainMenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainMenuPanelLayout.createSequentialGroup()
                .addGroup(mainMenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jSeparator3, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(mainMenuPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(mainMenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(scrollpaneStatus)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainMenuPanelLayout.createSequentialGroup()
                                .addGroup(mainMenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblPekerjaan)
                                    .addComponent(scrollpanePekerjaan, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(mainMenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblUang)
                                    .addComponent(scrollpaneUang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(mainMenuPanelLayout.createSequentialGroup()
                                .addComponent(lblKekenyangan)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(progbarKekenyangan, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblProgbarKekenyangan))
                            .addComponent(scrollPaneListSims, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainMenuPanelLayout.createSequentialGroup()
                                .addGroup(mainMenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblSimName)
                                    .addComponent(lblActiveSimInfo))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(mainMenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnLocation, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnInventory, javax.swing.GroupLayout.Alignment.TRAILING)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainMenuPanelLayout.createSequentialGroup()
                                .addComponent(lblMood)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(progbarMood, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblProgbarMood))
                            .addGroup(mainMenuPanelLayout.createSequentialGroup()
                                .addComponent(lblKesehatan)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(progbarKesehatan, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblProgbarKesehatan))
                            .addComponent(jSeparator4)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainMenuPanelLayout.createSequentialGroup()
                                .addGroup(mainMenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblObjectActions)
                                    .addComponent(lblSimActions))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnListObjects, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainMenuPanelLayout.createSequentialGroup()
                                .addGroup(mainMenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(btnBuildBuy, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnVisitOthers, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnEditRoom, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(mainMenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnMoveToRoom, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnPlaceFurniture, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(btnLookAtTime, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainMenuPanelLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(mainMenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainMenuPanelLayout.createSequentialGroup()
                                        .addComponent(btnChangeSim)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnAddSim))
                                    .addComponent(btnConfirm, javax.swing.GroupLayout.Alignment.TRAILING)))
                            .addGroup(mainMenuPanelLayout.createSequentialGroup()
                                .addGroup(mainMenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblStatus)
                                    .addComponent(lblSims, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainMenuPanelLayout.createSequentialGroup()
                                .addGroup(mainMenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblAction)
                                    .addComponent(jLabel1)
                                    .addComponent(lblObject))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(mainMenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(dropdownAction, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(dropdownObject, 0, 181, Short.MAX_VALUE)
                                    .addComponent(dropdownDirection, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
                .addGap(38, 38, 38))
        );
        mainMenuPanelLayout.setVerticalGroup(
            mainMenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainMenuPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(mainMenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSims)
                    .addComponent(btnChangeSim)
                    .addComponent(btnAddSim))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(scrollPaneListSims, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 3, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(mainMenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnInventory)
                    .addComponent(lblActiveSimInfo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(mainMenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSimName)
                    .addComponent(btnLocation))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(mainMenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblKekenyangan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblProgbarKekenyangan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(progbarKekenyangan, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(mainMenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(progbarMood, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblMood)
                    .addComponent(lblProgbarMood))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(mainMenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblKesehatan, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblProgbarKesehatan, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(progbarKesehatan, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblStatus)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(scrollpaneStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(mainMenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(mainMenuPanelLayout.createSequentialGroup()
                        .addGroup(mainMenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblPekerjaan)
                            .addComponent(lblUang))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(scrollpanePekerjaan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(mainMenuPanelLayout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(scrollpaneUang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 3, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblSimActions)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(mainMenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnVisitOthers)
                    .addComponent(btnMoveToRoom))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(mainMenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEditRoom)
                    .addComponent(btnPlaceFurniture))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(mainMenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnLookAtTime)
                    .addComponent(btnBuildBuy))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 6, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(mainMenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblObjectActions)
                    .addComponent(btnListObjects))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(mainMenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblObject)
                    .addComponent(dropdownObject, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(mainMenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAction)
                    .addComponent(dropdownDirection, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(mainMenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dropdownAction, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(8, 8, 8)
                .addComponent(btnConfirm)
                .addContainerGap(116, Short.MAX_VALUE))
        );

        menuBar.setPreferredSize(new java.awt.Dimension(256, 23));

        fileMenu.setMnemonic('f');
        fileMenu.setText("File");

        loadMenuItem.setMnemonic('o');
        loadMenuItem.setText("Load");
        fileMenu.add(loadMenuItem);

        saveAsMenuItem.setMnemonic('a');
        saveAsMenuItem.setText("Save As ...");
        saveAsMenuItem.setDisplayedMnemonicIndex(5);
        fileMenu.add(saveAsMenuItem);

        exitMenuItem.setMnemonic('x');
        exitMenuItem.setText("Exit");
        exitMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitMenuItemActionPerformed(evt);
            }
        });
        fileMenu.add(exitMenuItem);

        saveMenuItem.setMnemonic('s');
        saveMenuItem.setText("Save");
        fileMenu.add(saveMenuItem);

        menuBar.add(fileMenu);

        editMenu.setMnemonic('e');
        editMenu.setText("Edit");

        cutMenuItem.setMnemonic('t');
        cutMenuItem.setText("Cut");
        editMenu.add(cutMenuItem);

        copyMenuItem.setMnemonic('y');
        copyMenuItem.setText("Copy");
        editMenu.add(copyMenuItem);

        pasteMenuItem.setMnemonic('p');
        pasteMenuItem.setText("Paste");
        editMenu.add(pasteMenuItem);

        deleteMenuItem.setMnemonic('d');
        deleteMenuItem.setText("Delete");
        editMenu.add(deleteMenuItem);

        menuBar.add(editMenu);

        helpMenu.setMnemonic('h');
        helpMenu.setText("Help");

        contentsMenuItem.setMnemonic('c');
        contentsMenuItem.setText("Contents");
        helpMenu.add(contentsMenuItem);

        aboutMenuItem.setMnemonic('a');
        aboutMenuItem.setText("About");
        helpMenu.add(aboutMenuItem);

        menuBar.add(helpMenu);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(mainMenuPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(742, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(mainMenuPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exitMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitMenuItemActionPerformed
        System.exit(0);
    }//GEN-LAST:event_exitMenuItemActionPerformed

    private void btnChangeSimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChangeSimActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnChangeSimActionPerformed

    private void btnAddSimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddSimActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAddSimActionPerformed

    private void btnMoveToRoomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMoveToRoomActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnMoveToRoomActionPerformed

    private void btnListObjectsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListObjectsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnListObjectsActionPerformed

    private void btnEditRoomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditRoomActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEditRoomActionPerformed

    private void btnConfirmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnConfirmActionPerformed

    private void btnLookAtTimeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLookAtTimeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnLookAtTimeActionPerformed

    private void btnVisitOthersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVisitOthersActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnVisitOthersActionPerformed

    private void btnPlaceFurnitureActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPlaceFurnitureActionPerformed
        // TODO add your handling code here:
        setActionPlaceFurniture(!actionPlaceFurniture);
        if(actionPlaceFurniture)
        {
            btnPlaceFurniture.setBackground(Color.GREEN);
        }
        else
        {
            btnPlaceFurniture.setBackground(new Color(255,255,255));
        }
    }//GEN-LAST:event_btnPlaceFurnitureActionPerformed

    private void btnBuildBuyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuildBuyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBuildBuyActionPerformed

    private void btnInventoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInventoryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnInventoryActionPerformed

    private void dropdownActionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dropdownActionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dropdownActionActionPerformed

    private void dropdownDirectionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dropdownDirectionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dropdownDirectionActionPerformed

    private void dropdownObjectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dropdownObjectActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dropdownObjectActionPerformed

    public Boolean getActionPlaceFurniture() {
        return actionPlaceFurniture;
    }

    public void setActionPlaceFurniture(Boolean actionPlaceFurniture) {
        this.actionPlaceFurniture = actionPlaceFurniture;
    }

    public javax.swing.JComboBox<String> getFurniture() {
        return dropdownObject;
    }

    public javax.swing.JComboBox<String> getDirection() {
        return dropdownDirection;
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem aboutMenuItem;
    private javax.swing.JButton btnAddSim;
    private javax.swing.JButton btnBuildBuy;
    private javax.swing.JButton btnChangeSim;
    private javax.swing.JButton btnConfirm;
    private javax.swing.JButton btnEditRoom;
    private javax.swing.JButton btnInventory;
    private javax.swing.JButton btnListObjects;
    private javax.swing.JButton btnLocation;
    private javax.swing.JButton btnLookAtTime;
    private javax.swing.JButton btnMoveToRoom;
    private javax.swing.JButton btnPlaceFurniture;
    private javax.swing.JButton btnVisitOthers;
    private javax.swing.JMenuItem contentsMenuItem;
    private javax.swing.JMenuItem copyMenuItem;
    private javax.swing.JMenuItem cutMenuItem;
    private javax.swing.JMenuItem deleteMenuItem;
    private javax.swing.JComboBox<String> dropdownAction;
    private javax.swing.JComboBox<String> dropdownDirection;
    private javax.swing.JComboBox<String> dropdownObject;
    private javax.swing.JMenu editMenu;
    private javax.swing.JMenuItem exitMenuItem;
    private javax.swing.JMenu fileMenu;
    private javax.swing.JMenu helpMenu;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollBar jScrollBar1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JTextPane jTextPane3;
    private javax.swing.JLabel lblAction;
    private javax.swing.JLabel lblActiveSimInfo;
    private javax.swing.JLabel lblKekenyangan;
    private javax.swing.JLabel lblKesehatan;
    private javax.swing.JLabel lblMood;
    private javax.swing.JLabel lblObject;
    private javax.swing.JLabel lblObjectActions;
    private javax.swing.JLabel lblPekerjaan;
    private javax.swing.JLabel lblProgbarKekenyangan;
    private javax.swing.JLabel lblProgbarKesehatan;
    private javax.swing.JLabel lblProgbarMood;
    private javax.swing.JLabel lblSimActions;
    private javax.swing.JLabel lblSimName;
    private javax.swing.JLabel lblSims;
    private javax.swing.JLabel lblStatus;
    private javax.swing.JLabel lblUang;
    private javax.swing.JList<String> listSims;
    private javax.swing.JMenuItem loadMenuItem;
    private javax.swing.JPanel mainMenuPanel;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenuItem pasteMenuItem;
    private javax.swing.JProgressBar progbarKekenyangan;
    private javax.swing.JProgressBar progbarKesehatan;
    private javax.swing.JProgressBar progbarMood;
    private javax.swing.JMenuItem saveAsMenuItem;
    private javax.swing.JMenuItem saveMenuItem;
    private javax.swing.JScrollPane scrollPaneListSims;
    private javax.swing.JScrollPane scrollpanePekerjaan;
    private javax.swing.JScrollPane scrollpaneStatus;
    private javax.swing.JScrollPane scrollpaneUang;
    private javax.swing.JTextPane textPaneStatus;
    private javax.swing.JTextPane textpanePekerjaan;
    // End of variables declaration//GEN-END:variables

}
